import logging
import asyncio
import requests
import random
import uuid
import time
from urllib.parse import quote
from aiogram import Bot, Dispatcher, types, F
from aiogram.types import BufferedInputFile

# --- 🔑 CONFIGURATION ---
API_TOKEN = '8540275734:AAHA5OKbwzhQfdmS_Y73ij9AmuQy-WG0mNM'
ADMIN_ID = 7840042951
VERCEL_URL = "https://google-worker.vercel.app/api" 

logging.basicConfig(level=logging.INFO)
bot = Bot(token=API_TOKEN)
dp = Dispatcher()

class UnlimitedFireEngine:
    def get_ghost_headers(self):
        fake_ip = f"{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}"
        return {
            'User-Agent': "Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
            'X-Forwarded-For': fake_ip,
            'Origin': 'https://notegpt.io',
            'Referer': 'https://notegpt.io/ai-music-generator',
            'X-Requested-With': 'XMLHttpRequest'
        }

    async def tunnel_call(self, url, method="POST", payload=None, cookies=None):
        headers = self.get_ghost_headers()
        rid = f"{uuid.uuid4().hex[:8]}"
        data = {"url": url, "method": method, "payload": payload, "cookies": cookies, "headers": headers}
        
        # Adding a random query to the Vercel URL to break load-balancer stickiness
        target = f"{VERCEL_URL}?rotate={rid}&ts={time.time()}"
        return await asyncio.to_thread(requests.post, target, json=data, timeout=50)

engine = UnlimitedFireEngine()

@dp.message(F.text == "/start")
async def cmd_start(message: types.Message):
    await message.answer("🎵 **Songify AI Active**\nSend me any topic to generate studio-quality music!")

@dp.message(F.text)
async def handle_music(message: types.Message):
    if message.text.startswith("/"): return
    
    topic = message.text
    user_msg = await message.answer("📝 **Creating professional lyrics...**")
    
    try:
        # 1. Lyrics Generation
        p = f"Write professional song lyrics about '{topic}'. Structure: [Verse], [Chorus]. Match language."
        l_res = await asyncio.to_thread(requests.get, f"https://text.pollinations.ai/{quote(p)}", timeout=15)
        lyrics = l_res.text

        # 2. Composition via Tunnel
        await user_msg.edit_text("🎸 **Studio is processing your request...**")
        
        anon_id = str(uuid.uuid4())
        cookies = {'anonymous_user_id': anon_id, 'is_accepted_terms': '1'}
        payload = {
            "prompt": f"{topic} studio quality",
            "lyrics": lyrics[:2000],
            "duration": 0,
            "config": {"model": "sonic"}
        }

        res = await engine.tunnel_call("https://notegpt.io/api/v2/music/generate", payload=payload, cookies=cookies)
        
        # --- ADMIN DEBUG LOGGING ---
        scraped_ip = res.headers.get('X-Vercel-IP', 'Unknown')
        try:
            res_json = res.json()
            ng_code = res_json.get("code")
            ng_msg = res_json.get("msg", "No Message")
        except:
            ng_code = "PARSE_ERROR"
            ng_msg = res.text[:100]

        await bot.send_message(ADMIN_ID, f"🛠 **ADMIN LOG**\nIP: `{scraped_ip}`\nHTTP: {res.status_code}\nNoteGPT Code: `{ng_code}`\nMsg: {ng_msg}")

        if res.status_code == 200 and ng_code == 100000:
            cid = res_json["data"]["conversation_id"]
            
            # 3. Polling
            for i in range(1, 45):
                await asyncio.sleep(10)
                bar = "▓" * (i // 5) + "░" * (8 - (i // 5))
                await user_msg.edit_text(f"🎼 **Synthesizing audio...**\n`{bar}`")
                
                p_res = await engine.tunnel_call(f"https://notegpt.io/api/v2/music/status?conversation_id={cid}", method="GET", cookies=cookies)
                
                if p_res.status_code == 200:
                    s_data = p_res.json().get("data", {})
                    if s_data.get("status") == "success":
                        await user_msg.edit_text("✨ **Finalizing...**")
                        audio_url = s_data.get("music_url")
                        audio_bytes = await asyncio.to_thread(requests.get, audio_url)
                        
                        await message.answer_audio(
                            audio=BufferedInputFile(audio_bytes.content, filename=f"{topic[:10]}.mp3"),
                            caption=f"🎵 **Track:** {topic}\n✅ Generated by Songify AI"
                        )
                        await user_msg.delete()
                        return
        else:
            # Handle specific failure cases professionally
            await user_msg.edit_text("❌ **Studio is at capacity.** Please try again in 30 seconds.")

    except Exception as e:
        await bot.send_message(ADMIN_ID, f"❌ **CRITICAL ERROR:** {str(e)}")
        await user_msg.edit_text("❌ **An error occurred.** Please try a different topic.")

if __name__ == "__main__":
    asyncio.run(dp.start_polling(bot))
